server:
  port: 8083

spring:
  application:
    name: upi-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/globalunionpay?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: 6379

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: upi-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

upi:
  handle: globalunionpay
  daily-limit: 100000
  per-transaction-limit: 10000
